// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientId generated by hbm2java
 */
@Embeddable
public class ClientId implements java.io.Serializable {

	private int clientId;
	private Integer locatieId;
	private Integer zonaId;
	private Integer categorieId;
	private BigDecimal discount;
	private int pretFolosit;
	private int factura;
	private BigDecimal limitaCreditTotal;
	private BigDecimal soldTotal;

	public ClientId() {
	}

	public ClientId(int clientId, BigDecimal discount, int pretFolosit,
			int factura, BigDecimal limitaCreditTotal, BigDecimal soldTotal) {
		this.clientId = clientId;
		this.discount = discount;
		this.pretFolosit = pretFolosit;
		this.factura = factura;
		this.limitaCreditTotal = limitaCreditTotal;
		this.soldTotal = soldTotal;
	}

	public ClientId(int clientId, Integer locatieId, Integer zonaId,
			Integer categorieId, BigDecimal discount, int pretFolosit,
			int factura, BigDecimal limitaCreditTotal, BigDecimal soldTotal) {
		this.clientId = clientId;
		this.locatieId = locatieId;
		this.zonaId = zonaId;
		this.categorieId = categorieId;
		this.discount = discount;
		this.pretFolosit = pretFolosit;
		this.factura = factura;
		this.limitaCreditTotal = limitaCreditTotal;
		this.soldTotal = soldTotal;
	}

	@Column(name = "client_id", nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	@Column(name = "LocatieID")
	public Integer getLocatieId() {
		return this.locatieId;
	}

	public void setLocatieId(Integer locatieId) {
		this.locatieId = locatieId;
	}

	@Column(name = "zona_id")
	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

	@Column(name = "CategorieId")
	public Integer getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(Integer categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "Discount", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "PretFolosit", nullable = false)
	public int getPretFolosit() {
		return this.pretFolosit;
	}

	public void setPretFolosit(int pretFolosit) {
		this.pretFolosit = pretFolosit;
	}

	@Column(name = "Factura", nullable = false)
	public int getFactura() {
		return this.factura;
	}

	public void setFactura(int factura) {
		this.factura = factura;
	}

	@Column(name = "LimitaCreditTotal", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLimitaCreditTotal() {
		return this.limitaCreditTotal;
	}

	public void setLimitaCreditTotal(BigDecimal limitaCreditTotal) {
		this.limitaCreditTotal = limitaCreditTotal;
	}

	@Column(name = "SoldTotal", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getSoldTotal() {
		return this.soldTotal;
	}

	public void setSoldTotal(BigDecimal soldTotal) {
		this.soldTotal = soldTotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientId))
			return false;
		ClientId castOther = (ClientId) other;

		return (this.getClientId() == castOther.getClientId())
				&& ((this.getLocatieId() == castOther.getLocatieId()) || (this
						.getLocatieId() != null
						&& castOther.getLocatieId() != null && this
						.getLocatieId().equals(castOther.getLocatieId())))
				&& ((this.getZonaId() == castOther.getZonaId()) || (this
						.getZonaId() != null && castOther.getZonaId() != null && this
						.getZonaId().equals(castOther.getZonaId())))
				&& ((this.getCategorieId() == castOther.getCategorieId()) || (this
						.getCategorieId() != null
						&& castOther.getCategorieId() != null && this
						.getCategorieId().equals(castOther.getCategorieId())))
				&& ((this.getDiscount() == castOther.getDiscount()) || (this
						.getDiscount() != null
						&& castOther.getDiscount() != null && this
						.getDiscount().equals(castOther.getDiscount())))
				&& (this.getPretFolosit() == castOther.getPretFolosit())
				&& (this.getFactura() == castOther.getFactura())
				&& ((this.getLimitaCreditTotal() == castOther
						.getLimitaCreditTotal()) || (this
						.getLimitaCreditTotal() != null
						&& castOther.getLimitaCreditTotal() != null && this
						.getLimitaCreditTotal().equals(
								castOther.getLimitaCreditTotal())))
				&& ((this.getSoldTotal() == castOther.getSoldTotal()) || (this
						.getSoldTotal() != null
						&& castOther.getSoldTotal() != null && this
						.getSoldTotal().equals(castOther.getSoldTotal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClientId();
		result = 37 * result
				+ (getLocatieId() == null ? 0 : this.getLocatieId().hashCode());
		result = 37 * result
				+ (getZonaId() == null ? 0 : this.getZonaId().hashCode());
		result = 37
				* result
				+ (getCategorieId() == null ? 0 : this.getCategorieId()
						.hashCode());
		result = 37 * result
				+ (getDiscount() == null ? 0 : this.getDiscount().hashCode());
		result = 37 * result + this.getPretFolosit();
		result = 37 * result + this.getFactura();
		result = 37
				* result
				+ (getLimitaCreditTotal() == null ? 0 : this
						.getLimitaCreditTotal().hashCode());
		result = 37 * result
				+ (getSoldTotal() == null ? 0 : this.getSoldTotal().hashCode());
		return result;
	}

}
