// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClientiRute generated by hbm2java
 */
@Entity
@Table(name = "clienti_rute", schema = "public")
public class ClientiRute implements java.io.Serializable {

	private ClientiRuteId id;

	public ClientiRute() {
	}

	public ClientiRute(ClientiRuteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "clientId", column = @Column(name = "client_id")),
			@AttributeOverride(name = "rutaId", column = @Column(name = "ruta_id")),
			@AttributeOverride(name = "pozitie", column = @Column(name = "Pozitie")) })
	public ClientiRuteId getId() {
		return this.id;
	}

	public void setId(ClientiRuteId id) {
		this.id = id;
	}

}
