// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProduseEurobitId generated by hbm2java
 */
@Embeddable
public class ProduseEurobitId implements java.io.Serializable {

	private String stocId;
	private BigDecimal pretGross;

	public ProduseEurobitId() {
	}

	public ProduseEurobitId(String stocId, BigDecimal pretGross) {
		this.stocId = stocId;
		this.pretGross = pretGross;
	}

	@Column(name = "stoc_id", nullable = false, length = 10)
	public String getStocId() {
		return this.stocId;
	}

	public void setStocId(String stocId) {
		this.stocId = stocId;
	}

	@Column(name = "pret_gross", nullable = false, precision = 12)
	public BigDecimal getPretGross() {
		return this.pretGross;
	}

	public void setPretGross(BigDecimal pretGross) {
		this.pretGross = pretGross;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProduseEurobitId))
			return false;
		ProduseEurobitId castOther = (ProduseEurobitId) other;

		return ((this.getStocId() == castOther.getStocId()) || (this
				.getStocId() != null && castOther.getStocId() != null && this
				.getStocId().equals(castOther.getStocId())))
				&& ((this.getPretGross() == castOther.getPretGross()) || (this
						.getPretGross() != null
						&& castOther.getPretGross() != null && this
						.getPretGross().equals(castOther.getPretGross())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStocId() == null ? 0 : this.getStocId().hashCode());
		result = 37 * result
				+ (getPretGross() == null ? 0 : this.getPretGross().hashCode());
		return result;
	}

}
