// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
public class Product implements java.io.Serializable {

	private ProductId id;

	public Product() {
	}

	public Product(ProductId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "productName", column = @Column(name = "product_name")),
			@AttributeOverride(name = "aromaId", column = @Column(name = "AromaID")),
			@AttributeOverride(name = "grupaId", column = @Column(name = "GrupaID")),
			@AttributeOverride(name = "marcaId", column = @Column(name = "MarcaID")),
			@AttributeOverride(name = "tipId", column = @Column(name = "TipID")),
			@AttributeOverride(name = "litrajId", column = @Column(name = "LitrajID")),
			@AttributeOverride(name = "tipAmbalajId", column = @Column(name = "TipAmbalajID")),
			@AttributeOverride(name = "greutateId", column = @Column(name = "GreutateID")),
			@AttributeOverride(name = "producatorId", column = @Column(name = "ProducatorID")),
			@AttributeOverride(name = "umid", column = @Column(name = "UMID")),
			@AttributeOverride(name = "classId", column = @Column(name = "class_id")),
			@AttributeOverride(name = "price", column = @Column(name = "price", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "pret2", column = @Column(name = "Pret2", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "pret3", column = @Column(name = "Pret3", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "pret4", column = @Column(name = "Pret4", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "pret5", column = @Column(name = "Pret5", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "version", column = @Column(name = "Version", nullable = false)),
			@AttributeOverride(name = "anulat", column = @Column(name = "Anulat", nullable = false, length = 1)),
			@AttributeOverride(name = "valabilitate", column = @Column(name = "Valabilitate")),
			@AttributeOverride(name = "bucDisplay", column = @Column(name = "BucDisplay")),
			@AttributeOverride(name = "bucBax", column = @Column(name = "BucBax")),
			@AttributeOverride(name = "baxPal", column = @Column(name = "BaxPal")),
			@AttributeOverride(name = "symbol", column = @Column(name = "symbol")),
			@AttributeOverride(name = "gramaj", column = @Column(name = "Gramaj")),
			@AttributeOverride(name = "categorieId", column = @Column(name = "CategorieId")),
			@AttributeOverride(name = "customVersion", column = @Column(name = "CustomVersion", nullable = false)),
			@AttributeOverride(name = "blocatLaDiscount", column = @Column(name = "BlocatLaDiscount", nullable = false, length = 1)),
			@AttributeOverride(name = "discount", column = @Column(name = "Discount", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "blocareGratuitate", column = @Column(name = "BlocareGratuitate", nullable = false, length = 1)) })
	public ProductId getId() {
		return this.id;
	}

	public void setId(ProductId id) {
		this.id = id;
	}

}
