// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RuteId generated by hbm2java
 */
@Embeddable
public class RuteId implements java.io.Serializable {

	private int ruteId;
	private int version;
	private char anulat;
	private String denumire;
	private int agentId;
	private int ordonare;

	public RuteId() {
	}

	public RuteId(int ruteId, int version, char anulat, String denumire,
			int agentId, int ordonare) {
		this.ruteId = ruteId;
		this.version = version;
		this.anulat = anulat;
		this.denumire = denumire;
		this.agentId = agentId;
		this.ordonare = ordonare;
	}

	@Column(name = "rute_id", nullable = false)
	public int getRuteId() {
		return this.ruteId;
	}

	public void setRuteId(int ruteId) {
		this.ruteId = ruteId;
	}

	@Column(name = "Version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "Anulat", nullable = false, length = 1)
	public char getAnulat() {
		return this.anulat;
	}

	public void setAnulat(char anulat) {
		this.anulat = anulat;
	}

	@Column(name = "denumire", nullable = false)
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "agent_id", nullable = false)
	public int getAgentId() {
		return this.agentId;
	}

	public void setAgentId(int agentId) {
		this.agentId = agentId;
	}

	@Column(name = "Ordonare", nullable = false)
	public int getOrdonare() {
		return this.ordonare;
	}

	public void setOrdonare(int ordonare) {
		this.ordonare = ordonare;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuteId))
			return false;
		RuteId castOther = (RuteId) other;

		return (this.getRuteId() == castOther.getRuteId())
				&& (this.getVersion() == castOther.getVersion())
				&& (this.getAnulat() == castOther.getAnulat())
				&& ((this.getDenumire() == castOther.getDenumire()) || (this
						.getDenumire() != null
						&& castOther.getDenumire() != null && this
						.getDenumire().equals(castOther.getDenumire())))
				&& (this.getAgentId() == castOther.getAgentId())
				&& (this.getOrdonare() == castOther.getOrdonare());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRuteId();
		result = 37 * result + this.getVersion();
		result = 37 * result + this.getAnulat();
		result = 37 * result
				+ (getDenumire() == null ? 0 : this.getDenumire().hashCode());
		result = 37 * result + this.getAgentId();
		result = 37 * result + this.getOrdonare();
		return result;
	}

}
