// default package
// Generated Aug 13, 2015 8:44:07 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Terti generated by hbm2java
 */
@Entity
@Table(name = "terti", schema = "public")
public class Terti implements java.io.Serializable {

	private String tertId;
	private UserIdent userIdent;
	private Siruta siruta;
	private String cui;
	private String plt;
	private String categorieId;
	private String grupaId;
	private String clasaId;
	private String banca1;
	private String banca2;
	private String contbanca1;
	private String contbanca2;
	private String autorizatieTg;
	private String autorizatieCf;
	private String autorizatieBa;
	private String nrRegCom;
	private String localitate;
	private String judet;
	private String tara;
	private BigDecimal creditLimit;
	private Integer dayafter;
	private String telefon;
	private Date fmd;
	private Date lmd;
	private Date data0;
	private Character sw0;
	private Date operare;
	private Integer nivacc;
	private Boolean cms;
	private String atribFiscal;
	private String codIntern;
	private String persoana;
	private Date dataN;
	private Character sex;
	private Boolean tvai;
	private String cuin;
	private BigDecimal latit;
	private BigDecimal longit;
	private BigDecimal gprecizie;
	private String ttipId;
	private Integer trisc;
	private Integer tmodplata;
	private String idExt;
	private String zres1;
	private String zres2;
	private Boolean tipcf;
	private String denumire;
	private String adresa;
	private String email;
	private String fax;
	private String mobil1;
	private String mobil2;
	private String adrliv;
	private String codbare;

	public Terti() {
	}

	public Terti(String tertId) {
		this.tertId = tertId;
	}

	public Terti(String tertId, UserIdent userIdent, Siruta siruta, String cui,
			String plt, String categorieId, String grupaId, String clasaId,
			String banca1, String banca2, String contbanca1, String contbanca2,
			String autorizatieTg, String autorizatieCf, String autorizatieBa,
			String nrRegCom, String localitate, String judet, String tara,
			BigDecimal creditLimit, Integer dayafter, String telefon, Date fmd,
			Date lmd, Date data0, Character sw0, Date operare, Integer nivacc,
			Boolean cms, String atribFiscal, String codIntern, String persoana,
			Date dataN, Character sex, Boolean tvai, String cuin,
			BigDecimal latit, BigDecimal longit, BigDecimal gprecizie,
			String ttipId, Integer trisc, Integer tmodplata, String idExt,
			String zres1, String zres2, Boolean tipcf, String denumire,
			String adresa, String email, String fax, String mobil1,
			String mobil2, String adrliv, String codbare) {
		this.tertId = tertId;
		this.userIdent = userIdent;
		this.siruta = siruta;
		this.cui = cui;
		this.plt = plt;
		this.categorieId = categorieId;
		this.grupaId = grupaId;
		this.clasaId = clasaId;
		this.banca1 = banca1;
		this.banca2 = banca2;
		this.contbanca1 = contbanca1;
		this.contbanca2 = contbanca2;
		this.autorizatieTg = autorizatieTg;
		this.autorizatieCf = autorizatieCf;
		this.autorizatieBa = autorizatieBa;
		this.nrRegCom = nrRegCom;
		this.localitate = localitate;
		this.judet = judet;
		this.tara = tara;
		this.creditLimit = creditLimit;
		this.dayafter = dayafter;
		this.telefon = telefon;
		this.fmd = fmd;
		this.lmd = lmd;
		this.data0 = data0;
		this.sw0 = sw0;
		this.operare = operare;
		this.nivacc = nivacc;
		this.cms = cms;
		this.atribFiscal = atribFiscal;
		this.codIntern = codIntern;
		this.persoana = persoana;
		this.dataN = dataN;
		this.sex = sex;
		this.tvai = tvai;
		this.cuin = cuin;
		this.latit = latit;
		this.longit = longit;
		this.gprecizie = gprecizie;
		this.ttipId = ttipId;
		this.trisc = trisc;
		this.tmodplata = tmodplata;
		this.idExt = idExt;
		this.zres1 = zres1;
		this.zres2 = zres2;
		this.tipcf = tipcf;
		this.denumire = denumire;
		this.adresa = adresa;
		this.email = email;
		this.fax = fax;
		this.mobil1 = mobil1;
		this.mobil2 = mobil2;
		this.adrliv = adrliv;
		this.codbare = codbare;
	}

	@Id
	@Column(name = "tert_id", unique = true, nullable = false, length = 9)
	public String getTertId() {
		return this.tertId;
	}

	public void setTertId(String tertId) {
		this.tertId = tertId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public UserIdent getUserIdent() {
		return this.userIdent;
	}

	public void setUserIdent(UserIdent userIdent) {
		this.userIdent = userIdent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "siruta")
	public Siruta getSiruta() {
		return this.siruta;
	}

	public void setSiruta(Siruta siruta) {
		this.siruta = siruta;
	}

	@Column(name = "cui", length = 14)
	public String getCui() {
		return this.cui;
	}

	public void setCui(String cui) {
		this.cui = cui;
	}

	@Column(name = "plt", length = 2)
	public String getPlt() {
		return this.plt;
	}

	public void setPlt(String plt) {
		this.plt = plt;
	}

	@Column(name = "categorie_id", length = 4)
	public String getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(String categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "grupa_id", length = 4)
	public String getGrupaId() {
		return this.grupaId;
	}

	public void setGrupaId(String grupaId) {
		this.grupaId = grupaId;
	}

	@Column(name = "clasa_id", length = 4)
	public String getClasaId() {
		return this.clasaId;
	}

	public void setClasaId(String clasaId) {
		this.clasaId = clasaId;
	}

	@Column(name = "banca_1", length = 35)
	public String getBanca1() {
		return this.banca1;
	}

	public void setBanca1(String banca1) {
		this.banca1 = banca1;
	}

	@Column(name = "banca_2", length = 35)
	public String getBanca2() {
		return this.banca2;
	}

	public void setBanca2(String banca2) {
		this.banca2 = banca2;
	}

	@Column(name = "contbanca_1", length = 25)
	public String getContbanca1() {
		return this.contbanca1;
	}

	public void setContbanca1(String contbanca1) {
		this.contbanca1 = contbanca1;
	}

	@Column(name = "contbanca_2", length = 25)
	public String getContbanca2() {
		return this.contbanca2;
	}

	public void setContbanca2(String contbanca2) {
		this.contbanca2 = contbanca2;
	}

	@Column(name = "autorizatie_tg", length = 20)
	public String getAutorizatieTg() {
		return this.autorizatieTg;
	}

	public void setAutorizatieTg(String autorizatieTg) {
		this.autorizatieTg = autorizatieTg;
	}

	@Column(name = "autorizatie_cf", length = 20)
	public String getAutorizatieCf() {
		return this.autorizatieCf;
	}

	public void setAutorizatieCf(String autorizatieCf) {
		this.autorizatieCf = autorizatieCf;
	}

	@Column(name = "autorizatie_ba", length = 20)
	public String getAutorizatieBa() {
		return this.autorizatieBa;
	}

	public void setAutorizatieBa(String autorizatieBa) {
		this.autorizatieBa = autorizatieBa;
	}

	@Column(name = "nr_reg_com", length = 25)
	public String getNrRegCom() {
		return this.nrRegCom;
	}

	public void setNrRegCom(String nrRegCom) {
		this.nrRegCom = nrRegCom;
	}

	@Column(name = "localitate", length = 20)
	public String getLocalitate() {
		return this.localitate;
	}

	public void setLocalitate(String localitate) {
		this.localitate = localitate;
	}

	@Column(name = "judet", length = 15)
	public String getJudet() {
		return this.judet;
	}

	public void setJudet(String judet) {
		this.judet = judet;
	}

	@Column(name = "tara", length = 15)
	public String getTara() {
		return this.tara;
	}

	public void setTara(String tara) {
		this.tara = tara;
	}

	@Column(name = "credit_limit", precision = 13)
	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	@Column(name = "dayafter")
	public Integer getDayafter() {
		return this.dayafter;
	}

	public void setDayafter(Integer dayafter) {
		this.dayafter = dayafter;
	}

	@Column(name = "telefon", length = 14)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fmd", length = 13)
	public Date getFmd() {
		return this.fmd;
	}

	public void setFmd(Date fmd) {
		this.fmd = fmd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lmd", length = 13)
	public Date getLmd() {
		return this.lmd;
	}

	public void setLmd(Date lmd) {
		this.lmd = lmd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_0", length = 13)
	public Date getData0() {
		return this.data0;
	}

	public void setData0(Date data0) {
		this.data0 = data0;
	}

	@Column(name = "sw_0", length = 1)
	public Character getSw0() {
		return this.sw0;
	}

	public void setSw0(Character sw0) {
		this.sw0 = sw0;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operare", length = 29)
	public Date getOperare() {
		return this.operare;
	}

	public void setOperare(Date operare) {
		this.operare = operare;
	}

	@Column(name = "nivacc")
	public Integer getNivacc() {
		return this.nivacc;
	}

	public void setNivacc(Integer nivacc) {
		this.nivacc = nivacc;
	}

	@Column(name = "cms", precision = 1, scale = 0)
	public Boolean getCms() {
		return this.cms;
	}

	public void setCms(Boolean cms) {
		this.cms = cms;
	}

	@Column(name = "atrib_fiscal", length = 2)
	public String getAtribFiscal() {
		return this.atribFiscal;
	}

	public void setAtribFiscal(String atribFiscal) {
		this.atribFiscal = atribFiscal;
	}

	@Column(name = "cod_intern", length = 8)
	public String getCodIntern() {
		return this.codIntern;
	}

	public void setCodIntern(String codIntern) {
		this.codIntern = codIntern;
	}

	@Column(name = "persoana", length = 50)
	public String getPersoana() {
		return this.persoana;
	}

	public void setPersoana(String persoana) {
		this.persoana = persoana;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_n", length = 13)
	public Date getDataN() {
		return this.dataN;
	}

	public void setDataN(Date dataN) {
		this.dataN = dataN;
	}

	@Column(name = "sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "tvai")
	public Boolean getTvai() {
		return this.tvai;
	}

	public void setTvai(Boolean tvai) {
		this.tvai = tvai;
	}

	@Column(name = "cuin", length = 14)
	public String getCuin() {
		return this.cuin;
	}

	public void setCuin(String cuin) {
		this.cuin = cuin;
	}

	@Column(name = "latit", precision = 11, scale = 7)
	public BigDecimal getLatit() {
		return this.latit;
	}

	public void setLatit(BigDecimal latit) {
		this.latit = latit;
	}

	@Column(name = "longit", precision = 11, scale = 7)
	public BigDecimal getLongit() {
		return this.longit;
	}

	public void setLongit(BigDecimal longit) {
		this.longit = longit;
	}

	@Column(name = "gprecizie", precision = 11, scale = 7)
	public BigDecimal getGprecizie() {
		return this.gprecizie;
	}

	public void setGprecizie(BigDecimal gprecizie) {
		this.gprecizie = gprecizie;
	}

	@Column(name = "ttip_id", length = 4)
	public String getTtipId() {
		return this.ttipId;
	}

	public void setTtipId(String ttipId) {
		this.ttipId = ttipId;
	}

	@Column(name = "trisc")
	public Integer getTrisc() {
		return this.trisc;
	}

	public void setTrisc(Integer trisc) {
		this.trisc = trisc;
	}

	@Column(name = "tmodplata")
	public Integer getTmodplata() {
		return this.tmodplata;
	}

	public void setTmodplata(Integer tmodplata) {
		this.tmodplata = tmodplata;
	}

	@Column(name = "id_ext", length = 9)
	public String getIdExt() {
		return this.idExt;
	}

	public void setIdExt(String idExt) {
		this.idExt = idExt;
	}

	@Column(name = "zres1", length = 8)
	public String getZres1() {
		return this.zres1;
	}

	public void setZres1(String zres1) {
		this.zres1 = zres1;
	}

	@Column(name = "zres2", length = 8)
	public String getZres2() {
		return this.zres2;
	}

	public void setZres2(String zres2) {
		this.zres2 = zres2;
	}

	@Column(name = "tipcf", precision = 1, scale = 0)
	public Boolean getTipcf() {
		return this.tipcf;
	}

	public void setTipcf(Boolean tipcf) {
		this.tipcf = tipcf;
	}

	@Column(name = "denumire", length = 90)
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "adresa", length = 90)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "mobil1", length = 15)
	public String getMobil1() {
		return this.mobil1;
	}

	public void setMobil1(String mobil1) {
		this.mobil1 = mobil1;
	}

	@Column(name = "mobil2", length = 15)
	public String getMobil2() {
		return this.mobil2;
	}

	public void setMobil2(String mobil2) {
		this.mobil2 = mobil2;
	}

	@Column(name = "adrliv", length = 100)
	public String getAdrliv() {
		return this.adrliv;
	}

	public void setAdrliv(String adrliv) {
		this.adrliv = adrliv;
	}

	@Column(name = "codbare", length = 20)
	public String getCodbare() {
		return this.codbare;
	}

	public void setCodbare(String codbare) {
		this.codbare = codbare;
	}

}
