// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", schema = "public")
public class Client implements java.io.Serializable {

	private ClientId id;

	public Client() {
	}

	public Client(ClientId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "clientId", column = @Column(name = "client_id", nullable = false)),
			@AttributeOverride(name = "locatieId", column = @Column(name = "LocatieID")),
			@AttributeOverride(name = "zonaId", column = @Column(name = "zona_id")),
			@AttributeOverride(name = "categorieId", column = @Column(name = "CategorieId")),
			@AttributeOverride(name = "discount", column = @Column(name = "Discount", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "pretFolosit", column = @Column(name = "PretFolosit", nullable = false)),
			@AttributeOverride(name = "factura", column = @Column(name = "Factura", nullable = false)),
			@AttributeOverride(name = "limitaCreditTotal", column = @Column(name = "LimitaCreditTotal", nullable = false, precision = 131089, scale = 0)),
			@AttributeOverride(name = "soldTotal", column = @Column(name = "SoldTotal", nullable = false, precision = 131089, scale = 0)) })
	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

}
