// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProduseEurobit generated by hbm2java
 */
@Entity
@Table(name = "produse_eurobit", schema = "public")
public class ProduseEurobit implements java.io.Serializable {

	private ProduseEurobitId id;
	private String simbol;
	private String denumire;
	private String categorieId;
	private String grupaId;
	private String clasaId;
	private String clasa;
	private String grupa;
	private String categorie;

	public ProduseEurobit() {
	}

	public ProduseEurobit(ProduseEurobitId id) {
		this.id = id;
	}

	public ProduseEurobit(ProduseEurobitId id, String simbol, String denumire,
			String categorieId, String grupaId, String clasaId, String clasa,
			String grupa, String categorie) {
		this.id = id;
		this.simbol = simbol;
		this.denumire = denumire;
		this.categorieId = categorieId;
		this.grupaId = grupaId;
		this.clasaId = clasaId;
		this.clasa = clasa;
		this.grupa = grupa;
		this.categorie = categorie;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stocId", column = @Column(name = "stoc_id", nullable = false, length = 10)),
			@AttributeOverride(name = "pretGross", column = @Column(name = "pret_gross", nullable = false, precision = 12)) })
	public ProduseEurobitId getId() {
		return this.id;
	}

	public void setId(ProduseEurobitId id) {
		this.id = id;
	}

	@Column(name = "simbol", length = 13)
	public String getSimbol() {
		return this.simbol;
	}

	public void setSimbol(String simbol) {
		this.simbol = simbol;
	}

	@Column(name = "denumire", length = 45)
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "categorie_id", length = 4)
	public String getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(String categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "grupa_id", length = 4)
	public String getGrupaId() {
		return this.grupaId;
	}

	public void setGrupaId(String grupaId) {
		this.grupaId = grupaId;
	}

	@Column(name = "clasa_id", length = 4)
	public String getClasaId() {
		return this.clasaId;
	}

	public void setClasaId(String clasaId) {
		this.clasaId = clasaId;
	}

	@Column(name = "clasa", length = 35)
	public String getClasa() {
		return this.clasa;
	}

	public void setClasa(String clasa) {
		this.clasa = clasa;
	}

	@Column(name = "grupa", length = 35)
	public String getGrupa() {
		return this.grupa;
	}

	public void setGrupa(String grupa) {
		this.grupa = grupa;
	}

	@Column(name = "categorie", length = 35)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

}
