// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Rute generated by hbm2java
 */
@Entity
@Table(name = "rute", schema = "public")
public class Rute implements java.io.Serializable {

	private RuteId id;

	public Rute() {
	}

	public Rute(RuteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ruteId", column = @Column(name = "rute_id", nullable = false)),
			@AttributeOverride(name = "version", column = @Column(name = "Version", nullable = false)),
			@AttributeOverride(name = "anulat", column = @Column(name = "Anulat", nullable = false, length = 1)),
			@AttributeOverride(name = "denumire", column = @Column(name = "denumire", nullable = false)),
			@AttributeOverride(name = "agentId", column = @Column(name = "agent_id", nullable = false)),
			@AttributeOverride(name = "ordonare", column = @Column(name = "Ordonare", nullable = false)) })
	public RuteId getId() {
		return this.id;
	}

	public void setId(RuteId id) {
		this.id = id;
	}

}
