// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilizator generated by hbm2java
 */
@Entity
@Table(name = "utilizator", schema = "public")
public class Utilizator implements java.io.Serializable {

	private int utilizatorId;
	private String parola;
	private Integer sefId;
	private Integer zonaId;

	public Utilizator() {
	}

	public Utilizator(int utilizatorId, String parola) {
		this.utilizatorId = utilizatorId;
		this.parola = parola;
	}

	public Utilizator(int utilizatorId, String parola, Integer sefId,
			Integer zonaId) {
		this.utilizatorId = utilizatorId;
		this.parola = parola;
		this.sefId = sefId;
		this.zonaId = zonaId;
	}

	@Id
	@Column(name = "utilizator_id", unique = true, nullable = false)
	public int getUtilizatorId() {
		return this.utilizatorId;
	}

	public void setUtilizatorId(int utilizatorId) {
		this.utilizatorId = utilizatorId;
	}

	@Column(name = "parola", nullable = false)
	public String getParola() {
		return this.parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

	@Column(name = "sef_id")
	public Integer getSefId() {
		return this.sefId;
	}

	public void setSefId(Integer sefId) {
		this.sefId = sefId;
	}

	@Column(name = "zona_id")
	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

}
