// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name = "zona", schema = "public")
public class Zona implements java.io.Serializable {

	private ZonaId id;

	public Zona() {
	}

	public Zona(ZonaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "zonaId", column = @Column(name = "zona_id", nullable = false)),
			@AttributeOverride(name = "denumire", column = @Column(name = "denumire", nullable = false)),
			@AttributeOverride(name = "version", column = @Column(name = "Version", nullable = false)),
			@AttributeOverride(name = "nrAgenti", column = @Column(name = "NrAgenti", nullable = false)),
			@AttributeOverride(name = "nrAgentiRmn", column = @Column(name = "NrAgentiRMN", nullable = false)),
			@AttributeOverride(name = "nrAgentiTraditionali", column = @Column(name = "NrAgentiTraditionali", nullable = false)) })
	public ZonaId getId() {
		return this.id;
	}

	public void setId(ZonaId id) {
		this.id = id;
	}

}
