// default package
// Generated Aug 17, 2015 9:12:26 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProduseEurobit1 generated by hbm2java
 */
@Entity
@Table(name = "produse_eurobit1", schema = "public")
public class ProduseEurobit1 implements java.io.Serializable {

	private String stocId;
	private String simbol;
	private String denumire;
	private String categorieId;
	private String grupaId;
	private String clasaId;
	private String clasa;
	private String grupa;
	private String categorie;

	public ProduseEurobit1() {
	}

	public ProduseEurobit1(String stocId) {
		this.stocId = stocId;
	}

	public ProduseEurobit1(String stocId, String simbol, String denumire,
			String categorieId, String grupaId, String clasaId, String clasa,
			String grupa, String categorie) {
		this.stocId = stocId;
		this.simbol = simbol;
		this.denumire = denumire;
		this.categorieId = categorieId;
		this.grupaId = grupaId;
		this.clasaId = clasaId;
		this.clasa = clasa;
		this.grupa = grupa;
		this.categorie = categorie;
	}

	@Id
	@Column(name = "stoc_id", unique = true, nullable = false, length = 10)
	public String getStocId() {
		return this.stocId;
	}

	public void setStocId(String stocId) {
		this.stocId = stocId;
	}

	@Column(name = "simbol", length = 13)
	public String getSimbol() {
		return this.simbol;
	}

	public void setSimbol(String simbol) {
		this.simbol = simbol;
	}

	@Column(name = "denumire", length = 45)
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "categorie_id", length = 4)
	public String getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(String categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "grupa_id", length = 4)
	public String getGrupaId() {
		return this.grupaId;
	}

	public void setGrupaId(String grupaId) {
		this.grupaId = grupaId;
	}

	@Column(name = "clasa_id", length = 4)
	public String getClasaId() {
		return this.clasaId;
	}

	public void setClasaId(String clasaId) {
		this.clasaId = clasaId;
	}

	@Column(name = "clasa", length = 35)
	public String getClasa() {
		return this.clasa;
	}

	public void setClasa(String clasa) {
		this.clasa = clasa;
	}

	@Column(name = "grupa", length = 35)
	public String getGrupa() {
		return this.grupa;
	}

	public void setGrupa(String grupa) {
		this.grupa = grupa;
	}

	@Column(name = "categorie", length = 35)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

}
