// default package
// Generated Aug 17, 2015 9:12:26 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vterti generated by hbm2java
 */
@Entity
@Table(name = "vterti", schema = "public")
public class Vterti implements java.io.Serializable {

	private VtertiId id;

	public Vterti() {
	}

	public Vterti(VtertiId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sediu", column = @Column(name = "sediu", length = 90)),
			@AttributeOverride(name = "cui", column = @Column(name = "cui", length = 14)),
			@AttributeOverride(name = "plt", column = @Column(name = "plt", length = 2)),
			@AttributeOverride(name = "denumire", column = @Column(name = "denumire")),
			@AttributeOverride(name = "categorieId", column = @Column(name = "categorie_id", length = 4)),
			@AttributeOverride(name = "grupaId", column = @Column(name = "grupa_id", length = 4)),
			@AttributeOverride(name = "clasaId", column = @Column(name = "clasa_id", length = 4)),
			@AttributeOverride(name = "siruta", column = @Column(name = "siruta", precision = 6, scale = 0)),
			@AttributeOverride(name = "tertId", column = @Column(name = "tert_id", length = 9)),
			@AttributeOverride(name = "sw0", column = @Column(name = "sw_0", length = 1)),
			@AttributeOverride(name = "tvai", column = @Column(name = "tvai")),
			@AttributeOverride(name = "ttipId", column = @Column(name = "ttip_id", length = 4)),
			@AttributeOverride(name = "trisc", column = @Column(name = "trisc")),
			@AttributeOverride(name = "tmodplata", column = @Column(name = "tmodplata")) })
	public VtertiId getId() {
		return this.id;
	}

	public void setId(VtertiId id) {
		this.id = id;
	}

}
