package org.jlsoft.orders.connection.model;

// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComenziCvExtId generated by hbm2java
 */
@Embeddable
public class ComenziCvExtId1 implements java.io.Serializable {

	private String comId;
	private String nrlinie;

	public ComenziCvExtId1() {
	}

	public ComenziCvExtId1(String comId, String nrlinie) {
		this.comId = comId;
		this.nrlinie = nrlinie;
	}

	@Column(name = "com_id", nullable = false, length = 10)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "nrlinie", nullable = false, length = 3)
	public String getNrlinie() {
		return this.nrlinie;
	}

	public void setNrlinie(String nrlinie) {
		this.nrlinie = nrlinie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComenziCvExtId1))
			return false;
		ComenziCvExtId1 castOther = (ComenziCvExtId1) other;

		return ((this.getComId() == castOther.getComId()) || (this.getComId() != null
				&& castOther.getComId() != null && this.getComId().equals(
				castOther.getComId())))
				&& ((this.getNrlinie() == castOther.getNrlinie()) || (this
						.getNrlinie() != null && castOther.getNrlinie() != null && this
						.getNrlinie().equals(castOther.getNrlinie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result
				+ (getNrlinie() == null ? 0 : this.getNrlinie().hashCode());
		return result;
	}

}
