package org.jlsoft.orders.connection.model;

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComenziCvExt generated by hbm2java
 */
@Entity
@Table(name = "comenzi_cv_ext", schema = "public")
public class ComenziCvExt1 implements java.io.Serializable {

	private ComenziCvExtId1 id;
	private ComenziVExt1 comenziVExt;
	private String stocId;
	private String contGest;
	private BigDecimal cantitate;
	private BigDecimal cantitater;
	private BigDecimal livrat;
	private BigDecimal pretVanzare;
	private BigDecimal prDiscIncl;
	private BigDecimal discContr;
	private BigDecimal discCom;
	private BigDecimal pretGross;

	public ComenziCvExt1() {
	}

	public ComenziCvExt1(ComenziCvExtId1 id, ComenziVExt1 comenziVExt) {
		this.id = id;
		this.comenziVExt = comenziVExt;
	}

	public ComenziCvExt1(ComenziCvExtId1 id, ComenziVExt1 comenziVExt,
			String stocId, String contGest, BigDecimal cantitate,
			BigDecimal cantitater, BigDecimal livrat, BigDecimal pretVanzare,
			BigDecimal prDiscIncl, BigDecimal discContr, BigDecimal discCom,
			BigDecimal pretGross) {
		this.id = id;
		this.comenziVExt = comenziVExt;
		this.stocId = stocId;
		this.contGest = contGest;
		this.cantitate = cantitate;
		this.cantitater = cantitater;
		this.livrat = livrat;
		this.pretVanzare = pretVanzare;
		this.prDiscIncl = prDiscIncl;
		this.discContr = discContr;
		this.discCom = discCom;
		this.pretGross = pretGross;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 10)),
			@AttributeOverride(name = "nrlinie", column = @Column(name = "nrlinie", nullable = false, length = 3)) })
	public ComenziCvExtId1 getId() {
		return this.id;
	}

	public void setId(ComenziCvExtId1 id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "com_id", nullable = false, insertable = false, updatable = false)
	public ComenziVExt1 getComenziVExt() {
		return this.comenziVExt;
	}

	public void setComenziVExt(ComenziVExt1 comenziVExt) {
		this.comenziVExt = comenziVExt;
	}

	@Column(name = "stoc_id", length = 10)
	public String getStocId() {
		return this.stocId;
	}

	public void setStocId(String stocId) {
		this.stocId = stocId;
	}

	@Column(name = "cont_gest", length = 25)
	public String getContGest() {
		return this.contGest;
	}

	public void setContGest(String contGest) {
		this.contGest = contGest;
	}

	@Column(name = "cantitate", precision = 10, scale = 3)
	public BigDecimal getCantitate() {
		return this.cantitate;
	}

	public void setCantitate(BigDecimal cantitate) {
		this.cantitate = cantitate;
	}

	@Column(name = "cantitater", precision = 10, scale = 3)
	public BigDecimal getCantitater() {
		return this.cantitater;
	}

	public void setCantitater(BigDecimal cantitater) {
		this.cantitater = cantitater;
	}

	@Column(name = "livrat", precision = 10, scale = 3)
	public BigDecimal getLivrat() {
		return this.livrat;
	}

	public void setLivrat(BigDecimal livrat) {
		this.livrat = livrat;
	}

	@Column(name = "pret_vanzare", precision = 14)
	public BigDecimal getPretVanzare() {
		return this.pretVanzare;
	}

	public void setPretVanzare(BigDecimal pretVanzare) {
		this.pretVanzare = pretVanzare;
	}

	@Column(name = "pr_disc_incl", precision = 6)
	public BigDecimal getPrDiscIncl() {
		return this.prDiscIncl;
	}

	public void setPrDiscIncl(BigDecimal prDiscIncl) {
		this.prDiscIncl = prDiscIncl;
	}

	@Column(name = "disc_contr", precision = 6)
	public BigDecimal getDiscContr() {
		return this.discContr;
	}

	public void setDiscContr(BigDecimal discContr) {
		this.discContr = discContr;
	}

	@Column(name = "disc_com", precision = 6)
	public BigDecimal getDiscCom() {
		return this.discCom;
	}

	public void setDiscCom(BigDecimal discCom) {
		this.discCom = discCom;
	}

	@Column(name = "pret_gross", precision = 11)
	public BigDecimal getPretGross() {
		return this.pretGross;
	}

	public void setPretGross(BigDecimal pretGross) {
		this.pretGross = pretGross;
	}

}
