// default package
// Generated Aug 17, 2015 9:12:26 PM by Hibernate Tools 3.6.0
package org.jlsoft.orders.connection.model;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Siruta generated by hbm2java
 */
@Entity
@Table(name = "siruta", schema = "public")
public class Siruta implements java.io.Serializable {

	private int siruta;
	private Jud jud;
	private Boolean niv;
	private Integer sirsup;
	private Byte tip;
	private String denloc;
	private Character ult;
	private Character med;
	private Integer prefix;
	private Boolean regiune;
	private Integer codp;
	private Byte fsj;
	private String fs2;
	private String fs3;
	private Integer fsl;
	// private Set <Terti> tertis = new HashSet(0);

	public Siruta() {
	}

	public Siruta(int siruta) {
		this.siruta = siruta;
	}

	public Siruta(int siruta, Jud jud, Boolean niv, Integer sirsup, Byte tip,
			String denloc, Character ult, Character med, Integer prefix,
			Boolean regiune, Integer codp, Byte fsj, String fs2, String fs3,
			Integer fsl, Set <Terti> tertis) {
		this.siruta = siruta;
		this.jud = jud;
		this.niv = niv;
		this.sirsup = sirsup;
		this.tip = tip;
		this.denloc = denloc;
		this.ult = ult;
		this.med = med;
		this.prefix = prefix;
		this.regiune = regiune;
		this.codp = codp;
		this.fsj = fsj;
		this.fs2 = fs2;
		this.fs3 = fs3;
		this.fsl = fsl;
		// this.tertis = tertis;
	}

	@Id
	@Column(name = "siruta", unique = true, nullable = false, precision = 6, scale = 0)
	public int getSiruta() {
		return this.siruta;
	}

	public void setSiruta(int siruta) {
		this.siruta = siruta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jud")
	public Jud getJud() {
		return this.jud;
	}

	public void setJud(Jud jud) {
		this.jud = jud;
	}

	@Column(name = "niv", precision = 1, scale = 0)
	public Boolean getNiv() {
		return this.niv;
	}

	public void setNiv(Boolean niv) {
		this.niv = niv;
	}

	@Column(name = "sirsup", precision = 6, scale = 0)
	public Integer getSirsup() {
		return this.sirsup;
	}

	public void setSirsup(Integer sirsup) {
		this.sirsup = sirsup;
	}

	@Column(name = "tip", precision = 2, scale = 0)
	public Byte getTip() {
		return this.tip;
	}

	public void setTip(Byte tip) {
		this.tip = tip;
	}

	@Column(name = "denloc", length = 40)
	public String getDenloc() {
		return this.denloc;
	}

	public void setDenloc(String denloc) {
		this.denloc = denloc;
	}

	@Column(name = "ult", length = 1)
	public Character getUlt() {
		return this.ult;
	}

	public void setUlt(Character ult) {
		this.ult = ult;
	}

	@Column(name = "med", length = 1)
	public Character getMed() {
		return this.med;
	}

	public void setMed(Character med) {
		this.med = med;
	}

	@Column(name = "prefix", precision = 6, scale = 0)
	public Integer getPrefix() {
		return this.prefix;
	}

	public void setPrefix(Integer prefix) {
		this.prefix = prefix;
	}

	@Column(name = "regiune", precision = 1, scale = 0)
	public Boolean getRegiune() {
		return this.regiune;
	}

	public void setRegiune(Boolean regiune) {
		this.regiune = regiune;
	}

	@Column(name = "codp", precision = 6, scale = 0)
	public Integer getCodp() {
		return this.codp;
	}

	public void setCodp(Integer codp) {
		this.codp = codp;
	}

	@Column(name = "fsj", precision = 2, scale = 0)
	public Byte getFsj() {
		return this.fsj;
	}

	public void setFsj(Byte fsj) {
		this.fsj = fsj;
	}

	@Column(name = "fs2", length = 5)
	public String getFs2() {
		return this.fs2;
	}

	public void setFs2(String fs2) {
		this.fs2 = fs2;
	}

	@Column(name = "fs3", length = 7)
	public String getFs3() {
		return this.fs3;
	}

	public void setFs3(String fs3) {
		this.fs3 = fs3;
	}

	@Column(name = "fsl", precision = 6, scale = 0)
	public Integer getFsl() {
		return this.fsl;
	}

	public void setFsl(Integer fsl) {
		this.fsl = fsl;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siruta")
	public Set <Terti> getTertis() {
		return this.tertis;
	}

	public void setTertis(Set <Terti> tertis) {
		this.tertis = tertis;
	}
*/
}
