// Generated Aug 17, 2015 9:12:26 PM by Hibernate Tools 3.6.0
package org.jlsoft.orders.connection.model;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VtertiId generated by hbm2java
 */
@Embeddable
public class VtertiId implements java.io.Serializable {

	private String sediu;
	private String cui;
	private String plt;
	private String denumire;
	private String categorieId;
	private String grupaId;
	private String clasaId;
	private Integer siruta;
	private String tertId;
	private Character sw0;
	private Boolean tvai;
	private String ttipId;
	private Integer trisc;
	private Integer tmodplata;

	public VtertiId() {
	}

	public VtertiId(String sediu, String cui, String plt, String denumire,
			String categorieId, String grupaId, String clasaId, Integer siruta,
			String tertId, Character sw0, Boolean tvai, String ttipId,
			Integer trisc, Integer tmodplata) {
		this.sediu = sediu;
		this.cui = cui;
		this.plt = plt;
		this.denumire = denumire;
		this.categorieId = categorieId;
		this.grupaId = grupaId;
		this.clasaId = clasaId;
		this.siruta = siruta;
		this.tertId = tertId;
		this.sw0 = sw0;
		this.tvai = tvai;
		this.ttipId = ttipId;
		this.trisc = trisc;
		this.tmodplata = tmodplata;
	}

	@Column(name = "sediu", length = 90)
	public String getSediu() {
		return this.sediu;
	}

	public void setSediu(String sediu) {
		this.sediu = sediu;
	}

	@Column(name = "cui", length = 14)
	public String getCui() {
		return this.cui;
	}

	public void setCui(String cui) {
		this.cui = cui;
	}

	@Column(name = "plt", length = 2)
	public String getPlt() {
		return this.plt;
	}

	public void setPlt(String plt) {
		this.plt = plt;
	}

	@Column(name = "denumire")
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "categorie_id", length = 4)
	public String getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(String categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "grupa_id", length = 4)
	public String getGrupaId() {
		return this.grupaId;
	}

	public void setGrupaId(String grupaId) {
		this.grupaId = grupaId;
	}

	@Column(name = "clasa_id", length = 4)
	public String getClasaId() {
		return this.clasaId;
	}

	public void setClasaId(String clasaId) {
		this.clasaId = clasaId;
	}

	@Column(name = "siruta", precision = 6, scale = 0)
	public Integer getSiruta() {
		return this.siruta;
	}

	public void setSiruta(Integer siruta) {
		this.siruta = siruta;
	}

	@Column(name = "tert_id", length = 9)
	public String getTertId() {
		return this.tertId;
	}

	public void setTertId(String tertId) {
		this.tertId = tertId;
	}

	@Column(name = "sw_0", length = 1)
	public Character getSw0() {
		return this.sw0;
	}

	public void setSw0(Character sw0) {
		this.sw0 = sw0;
	}

	@Column(name = "tvai")
	public Boolean getTvai() {
		return this.tvai;
	}

	public void setTvai(Boolean tvai) {
		this.tvai = tvai;
	}

	@Column(name = "ttip_id", length = 4)
	public String getTtipId() {
		return this.ttipId;
	}

	public void setTtipId(String ttipId) {
		this.ttipId = ttipId;
	}

	@Column(name = "trisc")
	public Integer getTrisc() {
		return this.trisc;
	}

	public void setTrisc(Integer trisc) {
		this.trisc = trisc;
	}

	@Column(name = "tmodplata")
	public Integer getTmodplata() {
		return this.tmodplata;
	}

	public void setTmodplata(Integer tmodplata) {
		this.tmodplata = tmodplata;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtertiId))
			return false;
		VtertiId castOther = (VtertiId) other;

		return ((this.getSediu() == castOther.getSediu()) || (this.getSediu() != null
				&& castOther.getSediu() != null && this.getSediu().equals(
				castOther.getSediu())))
				&& ((this.getCui() == castOther.getCui()) || (this.getCui() != null
						&& castOther.getCui() != null && this.getCui().equals(
						castOther.getCui())))
				&& ((this.getPlt() == castOther.getPlt()) || (this.getPlt() != null
						&& castOther.getPlt() != null && this.getPlt().equals(
						castOther.getPlt())))
				&& ((this.getDenumire() == castOther.getDenumire()) || (this
						.getDenumire() != null
						&& castOther.getDenumire() != null && this
						.getDenumire().equals(castOther.getDenumire())))
				&& ((this.getCategorieId() == castOther.getCategorieId()) || (this
						.getCategorieId() != null
						&& castOther.getCategorieId() != null && this
						.getCategorieId().equals(castOther.getCategorieId())))
				&& ((this.getGrupaId() == castOther.getGrupaId()) || (this
						.getGrupaId() != null && castOther.getGrupaId() != null && this
						.getGrupaId().equals(castOther.getGrupaId())))
				&& ((this.getClasaId() == castOther.getClasaId()) || (this
						.getClasaId() != null && castOther.getClasaId() != null && this
						.getClasaId().equals(castOther.getClasaId())))
				&& ((this.getSiruta() == castOther.getSiruta()) || (this
						.getSiruta() != null && castOther.getSiruta() != null && this
						.getSiruta().equals(castOther.getSiruta())))
				&& ((this.getTertId() == castOther.getTertId()) || (this
						.getTertId() != null && castOther.getTertId() != null && this
						.getTertId().equals(castOther.getTertId())))
				&& ((this.getSw0() == castOther.getSw0()) || (this.getSw0() != null
						&& castOther.getSw0() != null && this.getSw0().equals(
						castOther.getSw0())))
				&& ((this.getTvai() == castOther.getTvai()) || (this.getTvai() != null
						&& castOther.getTvai() != null && this.getTvai()
						.equals(castOther.getTvai())))
				&& ((this.getTtipId() == castOther.getTtipId()) || (this
						.getTtipId() != null && castOther.getTtipId() != null && this
						.getTtipId().equals(castOther.getTtipId())))
				&& ((this.getTrisc() == castOther.getTrisc()) || (this
						.getTrisc() != null && castOther.getTrisc() != null && this
						.getTrisc().equals(castOther.getTrisc())))
				&& ((this.getTmodplata() == castOther.getTmodplata()) || (this
						.getTmodplata() != null
						&& castOther.getTmodplata() != null && this
						.getTmodplata().equals(castOther.getTmodplata())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSediu() == null ? 0 : this.getSediu().hashCode());
		result = 37 * result
				+ (getCui() == null ? 0 : this.getCui().hashCode());
		result = 37 * result
				+ (getPlt() == null ? 0 : this.getPlt().hashCode());
		result = 37 * result
				+ (getDenumire() == null ? 0 : this.getDenumire().hashCode());
		result = 37
				* result
				+ (getCategorieId() == null ? 0 : this.getCategorieId()
						.hashCode());
		result = 37 * result
				+ (getGrupaId() == null ? 0 : this.getGrupaId().hashCode());
		result = 37 * result
				+ (getClasaId() == null ? 0 : this.getClasaId().hashCode());
		result = 37 * result
				+ (getSiruta() == null ? 0 : this.getSiruta().hashCode());
		result = 37 * result
				+ (getTertId() == null ? 0 : this.getTertId().hashCode());
		result = 37 * result
				+ (getSw0() == null ? 0 : this.getSw0().hashCode());
		result = 37 * result
				+ (getTvai() == null ? 0 : this.getTvai().hashCode());
		result = 37 * result
				+ (getTtipId() == null ? 0 : this.getTtipId().hashCode());
		result = 37 * result
				+ (getTrisc() == null ? 0 : this.getTrisc().hashCode());
		result = 37 * result
				+ (getTmodplata() == null ? 0 : this.getTmodplata().hashCode());
		return result;
	}

}
