// default package
// Generated Jul 24, 2015 10:13:24 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientiRuteId generated by hbm2java
 */
@Embeddable
public class ClientiRuteId implements java.io.Serializable {

	private Integer clientId;
	private Integer rutaId;
	private Integer pozitie;

	public ClientiRuteId() {
	}

	public ClientiRuteId(Integer clientId, Integer rutaId, Integer pozitie) {
		this.clientId = clientId;
		this.rutaId = rutaId;
		this.pozitie = pozitie;
	}

	@Column(name = "client_id")
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "ruta_id")
	public Integer getRutaId() {
		return this.rutaId;
	}

	public void setRutaId(Integer rutaId) {
		this.rutaId = rutaId;
	}

	@Column(name = "Pozitie")
	public Integer getPozitie() {
		return this.pozitie;
	}

	public void setPozitie(Integer pozitie) {
		this.pozitie = pozitie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientiRuteId))
			return false;
		ClientiRuteId castOther = (ClientiRuteId) other;

		return ((this.getClientId() == castOther.getClientId()) || (this
				.getClientId() != null && castOther.getClientId() != null && this
				.getClientId().equals(castOther.getClientId())))
				&& ((this.getRutaId() == castOther.getRutaId()) || (this
						.getRutaId() != null && castOther.getRutaId() != null && this
						.getRutaId().equals(castOther.getRutaId())))
				&& ((this.getPozitie() == castOther.getPozitie()) || (this
						.getPozitie() != null && castOther.getPozitie() != null && this
						.getPozitie().equals(castOther.getPozitie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result
				+ (getRutaId() == null ? 0 : this.getRutaId().hashCode());
		result = 37 * result
				+ (getPozitie() == null ? 0 : this.getPozitie().hashCode());
		return result;
	}

}
